apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: key-funder-addresses-external-secret
  labels:
    {{- include "abacus.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "abacus.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: key-funder-addresses-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "abacus.labels" . | nindent 10 }}
        annotations:
          update-on-redeploy: "{{ now }}"
      data:
{{- range $context, $roles := .Values.abacus.contextsAndRolesToFund }}
        {{ $context }}-addresses.json: {{ printf "'{{ .%s_addresses | toString }}'" $context }}
{{- end }}
  data:
{{- range $context, $roles := .Values.abacus.contextsAndRolesToFund }}
  - secretKey: {{ $context }}_addresses
    remoteRef:
      key: {{ printf "%s-%s-key-addresses" $context $.Values.abacus.runEnv }}
{{- end }}
