image:
  repository: gcr.io/abacus-labs-dev/hyperlane-monorepo
  tag:
abacus:
  runEnv: testnet2
  # Used for fetching secrets
  chains: []
  contextFundingFrom: abacus
  # key = context, value = array of roles to fund
  contextsAndRolesToFund:
    abacus:
    - relayer
cronjob:
  schedule: "*/10 * * * *" # Every 10 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
externalSecrets:
  clusterSecretStore:
