[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
coingecko = { git = "https://github.com/hyperlane-xyz/coingecko-rs", tag = "2022-09-14-02" }
config = "0.13"
serde = {version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", default-features = false }
ethers = { git = "https://github.com/abacus-network/ethers-rs", tag = "2022-10-28-01" }
ethers-contract = { git = "https://github.com/abacus-network/ethers-rs", tag = "2022-10-28-01", features=["legacy"] }
thiserror = { version = "1.0", default-features = false }
async-trait = { version = "0.1", default-features = false }
futures-util = "0.3"
eyre = "0.6"
reqwest = { version = "0", features = ["json"]}
strum = "0.24"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.3"

abacus-core = { path = "../../abacus-core" }
abacus-base = { path = "../../abacus-base" }
abacus-ethereum = { path = "../../chains/abacus-ethereum" }
gelato = { path = "../../gelato" }
prometheus = "0.13"

[dev-dependencies]
tokio-test = "0.4"
abacus-test = { path = "../../abacus-test" }

[features]
default = ["abacus-base/color-eyre"]
oneline-errors = ["abacus-base/oneline-errors"]
