name: test

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        working-directory: solidity/khalani-core
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: solidity/khalani-core
        run: |
          forge test -vvv
        id: test

      - name: Run Slither core
        uses: crytic/slither-action@main
        continue-on-error: true
        id: slither
        with:
          target: "solidity/khalani-core"
          slither-config: "solidity/khalani-core/slither.config.json"
          sarif: results.sarif

     # - name: Upload SARIF file for core
      #  uses: github/codeql-action/upload-sarif@v2
       # id: upload-1
        #with:
         # sarif_file: ${{ steps.slither.outputs.sarif }}
            
      - name: Running coverage
        working-directory: solidity/khalani-core
        run: |
          forge coverage --report lcov
          sudo apt-get install lcov
          lcov --remove ./lcov.info -o ./lcov.info.pruned 'src/diamondCommons/*'  'test/Mock/*' 'test/utils/*'

      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          lcov-file: solidity/khalani-core/lcov.info.pruned
          github-token: ${{ secrets.GITHUB_TOKEN }}

