name: test

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  FOUNDRY_PROFILE: ci
  USDC_ETH_MIRROR : "0x65F45E64C7BDE86b61B3CEC594fb5FFcE15e8c11"
  USDC_AVAX_MIRROR : "0x7Ba52FC409B5683565fAF196825D5339a391D7a1"
  AXON_TEST_PAN : "0x00Af77a63F05acE63bebbA1Ca0286089585625C8"

  AXON_USDCETH_PAN_BPT : "0x4215A70E9B7557D3DeC5d5232Cf1DC26Da373af7"
  AXON_USDCAVAX_PAN_BPT : "0xC0Bf43e40D370D9cBB4fe0f0966226089C0f5c30"

  TOKEN_ADMIN : "0xdDF7F0d7bcCa30022Fe1D1a49f19f53A8d72eC41"
  GOERLI_INFURA_URL: ${{ secrets.GOERLI_INFURA_URL }}
  AXON_RPC_URL : ${{ secrets.AXON_RPC_URL }}
  FUJI_INFURA_URL : ${{ secrets.FUJI_INFURA_URL }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
        
      - name: Run Forge build
        working-directory: solidity/khalani-core
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: solidity/khalani-core
        run: |
          forge test -vvv
        id: test

      - name: Run Slither core
        uses: crytic/slither-action@main
        continue-on-error: true
        id: slither
        with:
        # see: https://github.com/crytic/slither-action/issues/42#issuecomment-1320062318
          ignore-compile: true
          target: "solidity/khalani-core"
          slither-config: "solidity/khalani-core/slither.config.json"
          sarif: results.sarif

     # - name: Upload SARIF file for core
      #  uses: github/codeql-action/upload-sarif@v2
       # id: upload-1
        #with:
         # sarif_file: ${{ steps.slither.outputs.sarif }}
            
      - name: Running coverage
        working-directory: solidity/khalani-core
        run: |
          forge coverage --report lcov
          sudo apt-get install lcov
          lcov --remove ./lcov.info -o ./lcov.info.pruned 'src/diamondCommons/*'  'test/Mock/*' 'test/utils/*'

      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          lcov-file: solidity/khalani-core/lcov.info.pruned
          github-token: ${{ secrets.GITHUB_TOKEN }}

